### ISSUE TITLE
youtube video playback stopped due to unauthorized overlay on top of player android

### ISSUE THREAD

**Issue by girubhai** [obipawan/youtube-recyclerview#1]
Thanks to provide great code for inline youtube player.

In your sample its working good,

But when I integrate it in my code, youtube video is auto paused and in device if I adjust youtube framelayout position via manual scroll at bottom its playing.  and in log it print as

youtube video playback stopped due to unauthorized overlay on top of player.......

Is there any solution ?

**Comment by Prateek218** [comment]
@girubhai have you got any solution the above problem you mention.

**Comment by obipawan** [comment]
Hi @girubhai @Prateek218
Youtube is known to pause the video whenever there's a `View` overlayed on top of it. The fastest way to figure out what `View` is being rendered on top is to use the Hierarchy Viewer.

**Comment by Thirupathi76** [comment]
After playing some videos in list, I am getting this.

YouTube video playback stopped due to unauthorized overlay on top of player. The YouTubePlayerView is not contained inside its ancestor android.widget.FrameLayout{1707c4f1 V.E..... ......I. 0,0-0,0}. The distances between the ancestor's edges and that of the YouTubePlayerView is: left: 0, top: 0, right: 0, bottom: 0 (these should all be positive).
